[project]
name = "namesearch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "faker>=36.1.1",
    "metaphone>=0.6",
    "typesense>=0.21.0",
]
